---
- name: validate role spec
  validate_role_spec:
    spec: configure_options.yaml

- block:
  - name: enable netconf
    include_tasks: includes/netconf.yaml

  - name: fetch yang model
    include_tasks: includes/fetch.yaml
  when: yang_fetch_schema|bool == true

- name: "spec: create directory '{{ yang_spec_dir }}' if not exist"
  file:
    path: "{{ yang_spec_dir }}"
    state: directory

- name: "spec: generate yang tree and config skeleton in json and xml format"
  set_fact:
    yang_spec_out: "{{ lookup('yang2spec', yang_file, search_path=yang_search_path, doctype=yang_doctype, annotations=yang_annotations) }}"

- name: "spec: copy json config structure to file {{ yang_json_config_file }}"
  copy:
    content: "{{ yang_spec_out['json_skeleton'] | from_json | to_nice_json}}"
    dest: "{{ yang_json_config_file }}"

- name: "spec: copy xml config structure to file {{ yang_xml_config_file }}"
  copy:
    content: "{{ yang_spec_out['xml_skeleton'] }}"
    dest: "{{ yang_xml_config_file }}"

- name: "spec: copy yang tree to file {{ yang_tree_file }}"
  copy:
    content: "{{ yang_spec_out['tree'] }}"
    dest: "{{ yang_tree_file }}"
