---
argument_spec:

  ansible_network_os:
    description:
      - Set the name of the Ansible network OS platform.
    required: true

  ansible_connection:
    description:
      - Name of the connection type used to connect to remote host
    required: true
    default: netconf
    choices: ['netconf']

  yang_config_file:
    description:
      - Provide a relative or absolute path to the json configuration file to be
        loaded onto the target network device.
    required: true
    type: str

  yang_model_name:
    description:
      - Name of yang module for which json configuration is defined
    required: true
    type: str
