---
# Download yang model in current working directory
# eg.
# git clone https://github.com/openconfig/public

- hosts: iosxr
  connection: netconf
  gather_facts: no
  tasks:

  - name: import role
    include_role:
      name: ansible-network.yang
      tasks_from: configure
    vars:
       yang_config_file: interfaces.json
       yang_model_name: openconfig-interfaces
       ansible_network_provider: cisco_iosxr
       yang_fetch_schema: False
       yang_file: "public/release/models/interfaces/openconfig-interfaces.yang"
       yang_search_path: "public/release/models"
