---
- hosts: iosxr
  connection: netconf
  gather_facts: no
  tasks:

  - name: import role
    include_role:
      name: ansible-network.yang
      tasks_from: configure
    vars:
       yang_config_file: interfaces.json
       yang_model_name: openconfig-interfaces
       ansible_network_provider: cisco_iosxr
