---
# Download yang model in current working directory
# eg.
# git clone https://github.com/openconfig/public

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: include yang role
    include_role:
      name: ansible-network.yang
      tasks_from: spec
    loop:
       - openconfig-interfaces
    loop_control:
      loop_var: yang_model_name
    vars:
       yang_fetch_schema: False
       yang_file: "public/release/models/interfaces/openconfig-interfaces.yang"
       yang_search_path: "public/release/models"
       ansible_network_provider: cisco_iosxr
